---
title: "salesData"
author: "Erika Vargas"
date: "May 4, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading the data
library(dplyr)
library(magrittr)
library(readxl)
sales_data <- read_excel("symetra_data.xlsx")
head(sales_data)
```

```{r}
#cleaning the data
sales_data <- sales_data[,-c(4,13,14,15)] #removes an empty column
class(sales_data) # the data is a dataframe
#renaming columns
names(sales_data)[1:11] =
  c("Ext_Channel", "Ext_Specialist", "ProducerID", "Parent", "Firm Name", "State", "PSuite CT", "ProductName", "Year" , "Month", "SalesAmount")

head(sales_data)


```

```{r}
#total unique producers 
total_producers <- subset(sales_data, !duplicated(ProducerID))
nrow(total_producers)
```


```{r}
#total sales amount by producer
SalesByProducer <- aggregate(SalesAmount~ProducerID,data=sales_data,FUN=sum)
# top 10 Producers
SalesByProducer %>%top_n(10)
# Bottom 10 Producers
SalesByProducer %>%top_n(-10)
```

```{r}
#looking at sales by Month
boxplot(log(SalesAmount)~ Month,data=total_producers, main="Sales by Month", 
   xlab="Month", ylab="Sales Amount")
```


```{r}
#import data with sales by year 
ProducerSalesByyear <- read_excel("salesDistinct.xlsx")
class(ProducerSalesByyear)
names(ProducerSalesByyear)[1] = c("ProducerID")
```


```{r}
#joining tables to consolidate the data
data <- merge(x = total_producers, y = ProducerSalesByyear, by = "ProducerID", all = TRUE)
head(data)
# I will delete the 219 column because of the values are N/A
data <- data[,-17]
```


#GROUPING BY YEARS
**I would like to look at the data by years and see if I found correlations between factorss for that first sale**


```{r}
# producer with first sale in 2014
one2014 <- data %>%
        filter(!is.na(data$`2014`), data$`2014`!=0, data$`2014` != "-" , data$Year == 2014,
               is.na(data$`2015`), is.na(data$`2016`), is.na(data$`2017`), is.na(data$`2018`))

str(one2014)
#changing character columns to factors 
one2014 <- mutate_at(one2014, vars(Ext_Channel,Ext_Specialist,Parent,`Firm Name`,State,`PSuite CT`, ProductName,Year, Month), as.factor)

```

```{r}
#looking at sales by month in 2014
boxplot(log(`2014`)~ Month,data=one2014, main="Sales by Month", 
   xlab="Month", ylab="Sales Amount")

#contigency tables
parent_Firmname <- table(one2014$`Firm Name`, one2014$Parent)
table(one2014$Ext_Specialist,one2014$Ext_Channel)
table(one2014$`PSuite CT`,one2014$Ext_Channel)
#checking for independency using chi-square test 
tbl = table(one2014$`PSuite CT`,one2014$Ext_Channel)
chi2 <- chisq.test(tbl)
chi2$statisti
chi2$p.value

# computing V. the smaller v, the lower the correlation)
sqrt(chi2$statistic / sum(tbl))

#ANALYZING numercial vs categorical variable using anova table 

fit <- aov(one2014$`2014` ~ one2014$State, data = one2014)
plot(fit)
```



```{r}
#visuals of the data
library(ggfortify)

### look what kind of principal component analysis can be done with categorical data

boxplot(log(`2014`)~ Ext_Channel,data=one2014, main="Sales by External Channel in 2014", 
   xlab="Ext.Channel", ylab="Sales Amount")

hist(log(one2014$`2014`), breaks = 50)

```




```{r}
#looking for possible predictors 
#state
regression2014 <- lm(log(`2014`) ~ State, data= one2014)
summary(regression2014)
plot(regression2014)
```













```{r}
#removing blank rows in production amount 

 sales_data[!(is.na(sales_data$SalesAmount) | sales_data$SalesAmount==""), ]
```

